# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('servings', models.PositiveIntegerField(null=True)),
                ('ingredients', models.TextField(null=True)),
                ('instructions', models.TextField(null=True)),
            ],
        ),
    ]
